options:
  port:
    type: string
    default: '9000'
    description: HTTP port
  access-key:
    type: string
    default: minio
    description: Access key
  secret-key:
    type: string
    default: ~
    description: Secret key
